import { Venue } from "./types";

export const venues: Venue[] = [
  {
    id: "toyo-eatery",
    name: "Toyo Eatery",
    area: "Makati",
    type: "food",
    vibe: ["foodie", "date", "upscale"],
    cost: 2500,
    duration: 90,
    opens: "18:00",
    closes: "22:00",
    weatherProof: true,
    blurb: "Modern Filipino tasting menu, internationally acclaimed",
    lat: 14.5547,
    lng: 121.0244,
  },
  {
    id: "wildflour-salcedo",
    name: "Wildflour Salcedo",
    area: "Makati",
    type: "food",
    vibe: ["brunch", "casual", "date"],
    cost: 600,
    duration: 60,
    opens: "07:00",
    closes: "22:00",
    weatherProof: true,
    blurb: "Beloved brunch spot, sourdough + croissants",
    lat: 14.5609,
    lng: 121.0227,
  },
  {
    id: "manam-maginhawa",
    name: "Manam Maginhawa",
    area: "QC",
    type: "food",
    vibe: ["foodie", "casual", "group", "local"],
    cost: 500,
    duration: 75,
    opens: "11:00",
    closes: "22:00",
    weatherProof: true,
    blurb: "Reimagined Filipino classics in three sizes",
    lat: 14.6407,
    lng: 121.0556,
  },
  {
    id: "sunnies-cafe-bgc",
    name: "Sunnies Café BGC",
    area: "BGC",
    type: "food",
    vibe: ["brunch", "date", "aesthetic"],
    cost: 700,
    duration: 60,
    opens: "08:00",
    closes: "23:00",
    weatherProof: true,
    blurb: "Pastel-pink café, Insta-famous pasta",
    lat: 14.5518,
    lng: 121.0509,
  },
  {
    id: "single-origin-bgc",
    name: "Single Origin BGC",
    area: "BGC",
    type: "food",
    vibe: ["coffee", "work", "chill"],
    cost: 350,
    duration: 45,
    opens: "07:00",
    closes: "23:00",
    weatherProof: true,
    blurb: "Specialty coffee + all-day breakfast",
    lat: 14.5547,
    lng: 121.0462,
  },
  {
    id: "ayala-museum",
    name: "Ayala Museum",
    area: "Makati",
    type: "culture",
    vibe: ["art", "date", "weird"],
    cost: 425,
    duration: 90,
    opens: "09:00",
    closes: "18:00",
    weatherProof: true,
    blurb: "Pre-colonial gold, dioramas, contemporary Filipino art",
    lat: 14.5569,
    lng: 121.0249,
  },
  {
    id: "mind-museum",
    name: "The Mind Museum",
    area: "BGC",
    type: "culture",
    vibe: ["family", "weird", "interactive"],
    cost: 750,
    duration: 120,
    opens: "09:00",
    closes: "18:00",
    weatherProof: true,
    blurb: "Hands-on science museum",
    lat: 14.5515,
    lng: 121.0462,
  },
  {
    id: "pinto-art-museum",
    name: "Pinto Art Museum",
    area: "Antipolo",
    type: "culture",
    vibe: ["art", "aesthetic", "date", "escape"],
    cost: 250,
    duration: 150,
    opens: "09:00",
    closes: "18:00",
    weatherProof: false,
    blurb: "Hilltop museum, Mediterranean architecture, panoramic views",
    lat: 14.5899,
    lng: 121.1807,
  },
  {
    id: "la-mesa-eco-park",
    name: "La Mesa Eco Park",
    area: "QC",
    type: "outdoor",
    vibe: ["nature", "family", "escape", "active"],
    cost: 50,
    duration: 120,
    opens: "06:00",
    closes: "18:00",
    weatherProof: false,
    blurb: "Forest reserve, biking + picnic",
    lat: 14.6955,
    lng: 121.0722,
  },
  {
    id: "qc-memorial-circle",
    name: "QC Memorial Circle",
    area: "QC",
    type: "outdoor",
    vibe: ["chill", "family", "local"],
    cost: 0,
    duration: 60,
    opens: "05:00",
    closes: "22:00",
    weatherProof: false,
    blurb: "Iconic QC park, jogging path",
    lat: 14.6515,
    lng: 121.0493,
  },
  {
    id: "the-curator",
    name: "The Curator",
    area: "Makati",
    type: "night",
    vibe: ["date", "upscale", "cocktails"],
    cost: 1200,
    duration: 90,
    opens: "18:00",
    closes: "02:00",
    weatherProof: true,
    blurb: "Speakeasy behind a coffee bar, Asia's-50-Best alum",
    lat: 14.5633,
    lng: 121.0144,
  },
  {
    id: "poblacion-bar-crawl",
    name: "Poblacion Bar Crawl",
    area: "Makati",
    type: "night",
    vibe: ["group", "party", "weird"],
    cost: 1500,
    duration: 180,
    opens: "19:00",
    closes: "03:00",
    weatherProof: true,
    blurb: "Walkable bar district — Bank Bar, OTO, ABV",
    lat: 14.5639,
    lng: 121.0138,
  },
  {
    id: "up-town-center-cinema",
    name: "UP Town Center Cinema",
    area: "QC",
    type: "night",
    vibe: ["chill", "date", "casual"],
    cost: 400,
    duration: 150,
    opens: "10:00",
    closes: "00:00",
    weatherProof: true,
    blurb: "Comfortable cinema, near food options",
    lat: 14.6577,
    lng: 121.0624,
  },
  {
    id: "cubao-expo",
    name: "Cubao Expo",
    area: "QC",
    type: "shop",
    vibe: ["weird", "aesthetic", "local", "vintage"],
    cost: 300,
    duration: 90,
    opens: "12:00",
    closes: "00:00",
    weatherProof: true,
    blurb: "Vintage shops, indie cafés, art galleries",
    lat: 14.6206,
    lng: 121.0553,
  },
  {
    id: "salcedo-saturday-market",
    name: "Salcedo Saturday Market",
    area: "Makati",
    type: "shop",
    vibe: ["brunch", "local", "foodie"],
    cost: 500,
    duration: 90,
    opens: "07:00",
    closes: "14:00",
    weatherProof: false,
    blurb: "Saturdays only — artisan food, produce, crafts",
    lat: 14.5602,
    lng: 121.0227,
  },
  {
    id: "maginhawa-food-street",
    name: "Maginhawa Food Street",
    area: "QC",
    type: "food",
    vibe: ["foodie", "group", "local", "cheap"],
    cost: 400,
    duration: 90,
    opens: "17:00",
    closes: "01:00",
    weatherProof: false,
    blurb: "Legendary QC food strip",
    lat: 14.6407,
    lng: 121.0556,
  },
];
